In [1]:
import requests
import os
import sys
import time
from dotenv import load_dotenv
import logging as log
import json
import pandas as pd
import pandas_ta as ta

from trading_scripts.api import utils
from trading_scripts.api.login import LoginManager
from trading_scripts.api.open_positions import OpenPositionsAPI
from trading_scripts.api.price_data import PriceData

In [2]:
# Configure logging to output to the notebook's standard output
log.basicConfig(level=log.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = log.getLogger()
logger.addHandler(log.StreamHandler(sys.stdout))

In [3]:
login_manager = LoginManager()

In [4]:
login_manager.login()

print(f"Auth: {login_manager.auth_trading_api}")
print(f"Cookie: {login_manager.cookie}")
print(f"UUID: {login_manager.system_uuid}")
print(f"RT Token: {login_manager.rt_token}")

auth_trading_api = login_manager.auth_trading_api
cookie = login_manager.cookie
UUID = login_manager.system_uuid
rt_token = login_manager.rt_token

2024-12-30 10:01:59,944 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-30 10:02:00,253 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "POST /mtr-core-edge/login HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "POST /mtr-core-edge/login HTTP/11" 200 None

2024-12-30 10:02:00,256 - root - INFO - Login successful. Tokens retrieved.

Login successful. Tokens retrieved.
Auth: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNdHIgVHJhZGluZyBBcGkiLCJ0cmFkaW5nQWNjb3VudElkIjoiMTIyMjciLCJlbWFpbCI6Im1hdEBnaXRjaGVndW1pLmNvbSIsInBhcnRuZXJJZCI6IjEiLCJpYXQiOjE3MzU1NzA5MjAsImV4cCI6NDYyMjQ3MDQyMn0.FpLLjaHySar3cmmxl0WZYkSVG9UA_yoL41cq9010PdU
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNTU3MTgyMCwianRpIjoiYmE5NWIzNDktZmE2MS00NjI1LWEzYWYtNjFkNzg4NGJlZWY1IiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.j_EpVu2Q2eruV1bohTqpnznxzTANC0lgE2JAmOyA-HY
UUID: 82b821d8-eeff-4352-ae2a-753c1daf8546
RT Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiJiYTk1YjM0OS1mYTYxLTQ2MjUtYTNhZi02MWQ3ODg0YmVlZjUiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczODI0OTMyMCwianRpIjoiYTU3ZTkyYmEtZDlkYi00M2Y4LWFiNzMtNzE3MGZiYWI0NjIyIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.zY8q8cuvTH53V9LldU4nXoYOrTzxv9zKA2eItcvDqOI

In [54]:
from urllib.parse import urlparse, parse_qs

def refresh_token():
    """Refresh the authentication token."""
    url = f"{utils.PLATFORM_URL}/mtr-backend/refresh-token"
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
        "Origin": "https://platform.citytradersimperium.com",
        "Referer": "https://platform.citytradersimperium.com/dashboard",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.8",
        "Sec-CH-UA": '"Brave";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
        "Sec-CH-UA-Mobile": "?0",
        "Sec-CH-UA-Platform": "Windows",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "Sec-GPC": "1",
    }

    session = requests.Session()
    session.headers.update(headers)
    session.cookies.set("rt", rt_token, domain="citytradersimperium.com", path="/mtr-backend/refresh-token")
    try:
        response = session.post(url, json={})
        response.raise_for_status()
        print("Response status code:", response.status_code)
        print("Response headers:", response.headers)
        print("Response cookies:", response.cookies)
        print("set-cookie header:", response.headers.get("Set-Cookie"))

        # Extract the updated co-auth token from cookies
        co_auth = next(
                    (
                        cookie.value
                        for cookie in response.cookies
                        if cookie.name == "co-auth"
                    ),
                    None,
                )
        new_rt_token = next(
                    (
                        cookie.value
                        for cookie in response.cookies
                        if cookie.name == "rt" and "mtr-backend" in cookie.path
                    ),
                    None,
                )
        if co_auth and rt_token:
            print(f"Token refreshed successfully. New co-auth token: {co_auth}")
            print(f"Token refreshed successfully. New rt token: {new_rt_token}")
            return co_auth, new_rt_token
        else:
            print("Failed to refresh token: No co-auth token in response.")
            return None
    except requests.exceptions.RequestException as e:
        print(f"Failed to refresh token: {e}")
        return None

In [55]:
refresh_token()

2024-12-25 18:05:56,085 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443
Starting new HTTPS connection (1): platform.citytradersimperium.com:443
Starting new HTTPS connection (1): platform.citytradersimperium.com:443
Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-25 18:05:56,459 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "POST /mtr-backend/refresh-token HTTP/11" 200 0

https://platform.citytradersimperium.com:443 "POST /mtr-backend/refresh-token HTTP/11" 200 0
https://platform.citytradersimperium.com:443 "POST /mtr-backend/refresh-token HTTP/11" 200 0
https://platform.citytradersimperium.com:443 "POST /mtr-backend/refresh-token HTTP/11" 200 0
https://platform.citytradersimperium.com:443 "POST /mtr-backend/refresh-token HTTP/11" 200 0
Response status code: 200
Response headers: {'Date': 'Wed, 25 Dec 2024 23:05:58 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': 'co-auth=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=platform.citytradersimperium.com; Path=/, co-auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNTE2ODg1OCwianRpIjoiNmY0ZWYyNmQtNTg2YS00ODMwLWE0NzctYzUzOWIwY2Y5OGRiIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.m7eMh93H55HG2oQ8T3sR0MAEKjVNciP8OSGqR5s6xpc; Max-Age=3600; Expires=Thu, 26-Dec-2024 00:05:58 GMT; Domain=citytradersimperium.com; Path=/, rt=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=platform.citytradersimperium.com; Path=/mtr-backend/refresh-token; Secure; HttpOnly, rt=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=platform.citytradersimperium.com; Path=/mtr-core-edge/refresh-token; Secure; HttpOnly, rt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiI2ZjRlZjI2ZC01ODZhLTQ4MzAtYTQ3Ny1jNTM5YjBjZjk4ZGIiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNzg0NjM0NiwianRpIjoiODFhZDU1ZGYtNzdmYi00NjBiLTg4NjAtZWFkNDVhOWM1Y2NhIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.Y_HZ4fof9t2rJv8HFD1WlEFb0epCxsMRBUV2KXCk9ts; Max-Age=31536000; Expires=Thu, 25-Dec-2025 23:05:58 GMT; Domain=citytradersimperium.com; Path=/mtr-backend/refresh-token; Secure; HttpOnly, rt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiI2ZjRlZjI2ZC01ODZhLTQ4MzAtYTQ3Ny1jNTM5YjBjZjk4ZGIiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNzg0NjM0NiwianRpIjoiODFhZDU1ZGYtNzdmYi00NjBiLTg4NjAtZWFkNDVhOWM1Y2NhIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.Y_HZ4fof9t2rJv8HFD1WlEFb0epCxsMRBUV2KXCk9ts; Max-Age=31536000; Expires=Thu, 25-Dec-2025 23:05:58 GMT; Domain=citytradersimperium.com; Path=/mtr-core-edge/refresh-token; Secure; HttpOnly, rt=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=citytradersimperium.com; Path=/mtr-backend/refresh-tokens; Secure; HttpOnly, rt=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=platform.citytradersimperium.com; Path=/mtr-backend/refresh-tokens; Secure; HttpOnly', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '8f7c7a9a7c653b8f-IAD', 'alt-svc': 'h3=":443"; ma=86400'}
Response cookies: <RequestsCookieJar[<Cookie co-auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNTE2ODg1OCwianRpIjoiNmY0ZWYyNmQtNTg2YS00ODMwLWE0NzctYzUzOWIwY2Y5OGRiIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.m7eMh93H55HG2oQ8T3sR0MAEKjVNciP8OSGqR5s6xpc for .citytradersimperium.com/>, <Cookie rt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiI2ZjRlZjI2ZC01ODZhLTQ4MzAtYTQ3Ny1jNTM5YjBjZjk4ZGIiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNzg0NjM0NiwianRpIjoiODFhZDU1ZGYtNzdmYi00NjBiLTg4NjAtZWFkNDVhOWM1Y2NhIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.Y_HZ4fof9t2rJv8HFD1WlEFb0epCxsMRBUV2KXCk9ts for .citytradersimperium.com/mtr-backend/refresh-token>, <Cookie rt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiI2ZjRlZjI2ZC01ODZhLTQ4MzAtYTQ3Ny1jNTM5YjBjZjk4ZGIiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNzg0NjM0NiwianRpIjoiODFhZDU1ZGYtNzdmYi00NjBiLTg4NjAtZWFkNDVhOWM1Y2NhIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.Y_HZ4fof9t2rJv8HFD1WlEFb0epCxsMRBUV2KXCk9ts for .citytradersimperium.com/mtr-core-edge/refresh-token>]>
set-cookie header: co-auth=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=platform.citytradersimperium.com; Path=/, co-auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNTE2ODg1OCwianRpIjoiNmY0ZWYyNmQtNTg2YS00ODMwLWE0NzctYzUzOWIwY2Y5OGRiIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.m7eMh93H55HG2oQ8T3sR0MAEKjVNciP8OSGqR5s6xpc; Max-Age=3600; Expires=Thu, 26-Dec-2024 00:05:58 GMT; Domain=citytradersimperium.com; Path=/, rt=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=platform.citytradersimperium.com; Path=/mtr-backend/refresh-token; Secure; HttpOnly, rt=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=platform.citytradersimperium.com; Path=/mtr-core-edge/refresh-token; Secure; HttpOnly, rt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiI2ZjRlZjI2ZC01ODZhLTQ4MzAtYTQ3Ny1jNTM5YjBjZjk4ZGIiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNzg0NjM0NiwianRpIjoiODFhZDU1ZGYtNzdmYi00NjBiLTg4NjAtZWFkNDVhOWM1Y2NhIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.Y_HZ4fof9t2rJv8HFD1WlEFb0epCxsMRBUV2KXCk9ts; Max-Age=31536000; Expires=Thu, 25-Dec-2025 23:05:58 GMT; Domain=citytradersimperium.com; Path=/mtr-backend/refresh-token; Secure; HttpOnly, rt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiI2ZjRlZjI2ZC01ODZhLTQ4MzAtYTQ3Ny1jNTM5YjBjZjk4ZGIiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNzg0NjM0NiwianRpIjoiODFhZDU1ZGYtNzdmYi00NjBiLTg4NjAtZWFkNDVhOWM1Y2NhIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.Y_HZ4fof9t2rJv8HFD1WlEFb0epCxsMRBUV2KXCk9ts; Max-Age=31536000; Expires=Thu, 25-Dec-2025 23:05:58 GMT; Domain=citytradersimperium.com; Path=/mtr-core-edge/refresh-token; Secure; HttpOnly, rt=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=citytradersimperium.com; Path=/mtr-backend/refresh-tokens; Secure; HttpOnly, rt=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Domain=platform.citytradersimperium.com; Path=/mtr-backend/refresh-tokens; Secure; HttpOnly
Token refreshed successfully. New co-auth token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNTE2ODg1OCwianRpIjoiNmY0ZWYyNmQtNTg2YS00ODMwLWE0NzctYzUzOWIwY2Y5OGRiIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.m7eMh93H55HG2oQ8T3sR0MAEKjVNciP8OSGqR5s6xpc
Token refreshed successfully. New rt token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiI2ZjRlZjI2ZC01ODZhLTQ4MzAtYTQ3Ny1jNTM5YjBjZjk4ZGIiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNzg0NjM0NiwianRpIjoiODFhZDU1ZGYtNzdmYi00NjBiLTg4NjAtZWFkNDVhOWM1Y2NhIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.Y_HZ4fof9t2rJv8HFD1WlEFb0epCxsMRBUV2KXCk9ts

('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNTE2ODg1OCwianRpIjoiNmY0ZWYyNmQtNTg2YS00ODMwLWE0NzctYzUzOWIwY2Y5OGRiIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.m7eMh93H55HG2oQ8T3sR0MAEKjVNciP8OSGqR5s6xpc',
 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X3V1aWQiOiJjZWZjZjE4Ny03YjlhLTRmZTItOTg4YS1hZDk3YWU0Nzc5NDMiLCJtYW5hZ2VyX3Njb3BlIjoiY2VmY2YxODctN2I5YS00ZmUyLTk4OGEtYWQ5N2FlNDc3OTQzIiwidXNlcl9uYW1lIjoibWF0QGdpdGNoZWd1bWkuY29tOjEiLCJmbCI6bnVsbCwic2NvcGUiOltdLCJhdGkiOiI2ZjRlZjI2ZC01ODZhLTQ4MzAtYTQ3Ny1jNTM5YjBjZjk4ZGIiLCJwYXJ0bmVySWQiOjEsImV4cCI6MTczNzg0NjM0NiwianRpIjoiODFhZDU1ZGYtNzdmYi00NjBiLTg4NjAtZWFkNDVhOWM1Y2NhIiwiZW1haWwiOiJtYXRAZ2l0Y2hlZ3VtaS5jb20iLCJhdXRob3JpdGllcyI6WyJFTUFJTF9SRUFEIiwiUEhPTkVfUkVBRCIsIlJPTEVfVVNFUiIsIlVTRVIiXSwiY2xpZW50X2lkIjoibGl2ZU10cjFDbGllbnQifQ.Y_HZ4fof9t2rJv8HFD1WlEFb0epCxsMRBUV2KXCk9ts')

In [15]:
def get_symbol_data(login_manager, symbol):
    """Get the latest news for a symbol."""
    url = f"{utils.PLATFORM_URL}/market-data-api/{login_manager.system_uuid}/api/trading-view/symbols?symbol={symbol}"
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
        "Origin": "https://platform.citytradersimperium.com",
        "Referer": "https://platform.citytradersimperium.com/dashboard",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.8",
        "Sec-CH-UA": '"Brave";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
        "Sec-CH-UA-Mobile": "?0",
        "Sec-CH-UA-Platform": "Windows",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "Sec-GPC": "1",
    }

    session = requests.Session()
    session.headers.update(headers)
    session.cookies.set("co-auth", cookie, domain="citytradersimperium.com", path="/mtr-backend/refresh-token")
    try:
        response = session.get(url)
        response.raise_for_status()
        data = response.json()
        return data
    except requests.exceptions.RequestException as e:
        print(f"Failed to get symbol data: {e}")
        return None

In [16]:
symbols = ["EURUSD", "BTCUSDC", "US500", "US30"]
for symbol in symbols:
    data = get_symbol_data(login_manager, symbol)
    print(f"Symbol: {symbol}: {json.dumps(data, indent=4)}")

2024-12-30 09:44:22,317 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-30 09:44:22,708 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/symbols?symbol=EURUSD HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/symbols?symbol=EURUSD HTTP/11" 200 None

2024-12-30 09:44:22,711 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Symbol: EURUSD: {
    "name": "EURUSD",
    "ticker": "EURUSD",
    "description": "Euro vs United States Dollar",
    "exchange-listed": "",
    "exchange-traded": "",
    "minmovement": 1,
    "minmovement2": 0,
    "pricescale": 100000,
    "timezone": "Etc/UTC",
    "type": "FOREX",
    "supported-resolutions": [
        "1",
        "3",
        "5",
        "15",
        "30",
        "60",
        "240",
        "D",
        "W",
        "M"
    ],
    "has-intraday": true,
    "visible-plots-set": "ohlc",
    "pointvalue": 1
}
Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-30 09:44:22,912 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/symbols?symbol=BTCUSDC HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/symbols?symbol=BTCUSDC HTTP/11" 200 None

2024-12-30 09:44:22,914 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Symbol: BTCUSDC: {
    "name": "BTCUSDC",
    "ticker": "BTCUSDC",
    "description": "Bitcoin",
    "exchange-listed": "",
    "exchange-traded": "",
    "minmovement": 1,
    "minmovement2": 0,
    "pricescale": 100,
    "timezone": "Etc/UTC",
    "type": "FOREXCFD",
    "supported-resolutions": [
        "1",
        "3",
        "5",
        "15",
        "30",
        "60",
        "240",
        "D",
        "W",
        "M"
    ],
    "has-intraday": true,
    "visible-plots-set": "ohlc",
    "pointvalue": 1
}
Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-30 09:44:23,289 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/symbols?symbol=US500 HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/symbols?symbol=US500 HTTP/11" 200 None

2024-12-30 09:44:23,294 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Symbol: US500: {
    "name": "US500",
    "ticker": "US500",
    "description": "US 500 Index",
    "exchange-listed": "",
    "exchange-traded": "",
    "minmovement": 1,
    "minmovement2": 0,
    "pricescale": 100,
    "timezone": "Etc/UTC",
    "type": "CFD",
    "supported-resolutions": [
        "1",
        "3",
        "5",
        "15",
        "30",
        "60",
        "240",
        "D",
        "W",
        "M"
    ],
    "has-intraday": true,
    "visible-plots-set": "ohlc",
    "pointvalue": 1
}
Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-30 09:44:23,492 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/symbols?symbol=US30 HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/symbols?symbol=US30 HTTP/11" 200 None
Symbol: US30: {
    "name": "US30",
    "ticker": "US30",
    "description": "US 30 Index",
    "exchange-listed": "",
    "exchange-traded": "",
    "minmovement": 1,
    "minmovement2": 0,
    "pricescale": 100,
    "timezone": "Etc/UTC",
    "type": "CFD",
    "supported-resolutions": [
        "1",
        "3",
        "5",
        "15",
        "30",
        "60",
        "240",
        "D",
        "W",
        "M"
    ],
    "has-intraday": true,
    "visible-plots-set": "ohlc",
    "pointvalue": 1
}

In [58]:
def get_balance(login_manager):
    """Get the account balance information."""
    url = f"{utils.PLATFORM_URL}/mtr-api/{login_manager.system_uuid}/balance"
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
        "Origin": f"{utils.PLATFORM_URL}",
        "Referer": f"{utils.PLATFORM_URL}/dashboard",
        "Auth-trading-api": login_manager.auth_trading_api,
        "Cookie": f"co-auth={login_manager.cookie}",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.8",
        "Sec-CH-UA": '"Brave";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
        "Sec-CH-UA-Mobile": "?0",
        "Sec-CH-UA-Platform": "Windows",
        "Sec-Fetch-Dest": "empty",
        "Sec-Fetch-Mode": "cors",
        "Sec-Fetch-Site": "same-origin",
        "Sec-GPC": "1",
    }

    session = requests.Session()
    session.headers.update(headers)
    try:
        response = session.get(url)
        response.raise_for_status()
        data = response.json()
        return data
    except requests.exceptions.RequestException as e:
        print(f"Failed to get balance data: {e}")
        return None

In [59]:
get_balance(login_manager)

2024-12-25 18:06:09,023 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443
Starting new HTTPS connection (1): platform.citytradersimperium.com:443
Starting new HTTPS connection (1): platform.citytradersimperium.com:443
Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-25 18:06:09,441 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/balance HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/balance HTTP/11" 200 None
https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/balance HTTP/11" 200 None
https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/balance HTTP/11" 200 None
https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/balance HTTP/11" 200 None

{'balance': '2365.96',
 'equity': '2371.94',
 'freeMargin': '1879.33',
 'marginLevel': '481.50',
 'credit': '0.00',
 'currency': 'USD',
 'margin': '492.61',
 'profit': '5.98',
 'netProfit': '5.98',
 'currencyPrecision': 2}

In [13]:
utils.fetch_open_positions_once(login_manager)

2024-12-27 19:57:05,903 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-27 19:57:06,275 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/open-positions HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/open-positions HTTP/11" 200 None

{'positions': [{'id': 'W963704386443530',
   'symbol': 'BTCUSDC',
   'alias': 'BTCUSDC',
   'volume': 0.02,
   'side': 'SELL',
   'openTime': '2024-12-28T00:57:03',
   'openTimeMillis': 1735347423281,
   'openPrice': 94354.4,
   'stopLoss': 94761.13,
   'takeProfit': 0.0,
   'trailingDistance': 0,
   'swap': 0.0,
   'profit': -0.76,
   'netProfit': -0.76,
   'currentPrice': 94392.5,
   'commission': 0.0,
   'positions': [{'id': 'W963704386443530',
     'symbol': 'BTCUSDC',
     'alias': 'BTCUSDC',
     'volume': '0.02',
     'oldPartialVolume': None,
     'side': 'SELL',
     'openTime': '2024-12-28T00:57:03',
     'openPrice': '94354.40',
     'swap': '0.00',
     'profit': '-0.76',
     'netProfit': '-0.76',
     'currentPrice': '94392.50',
     'commission': '0.00'}]}]}

In [19]:
price_data = PriceData(login_manager)
historical_data = price_data.fetch_market_data("EURUSD", 5, 5000)
df = pd.DataFrame(historical_data)
df.tail()

2024-12-28 00:15:28,548 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-28 00:15:29,112 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/history?symbol=EURUSD&resolution=5&from=1733862928&to=1735362928&shouldRetrieveOnlyFromCache=true&countback=5000 HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/history?symbol=EURUSD&resolution=5&from=1733862928&to=1735362928&shouldRetrieveOnlyFromCache=true&countback=5000 HTTP/11" 200 None

                  t        o        h        l        c   s
2995  1735335300000  1.04239  1.04239  1.04219  1.04225  ok
2996  1735335600000  1.04225  1.04227  1.04222  1.04222  ok
2997  1735335900000  1.04222  1.04232  1.04219  1.04229  ok
2998  1735336200000  1.04228  1.04243  1.04227  1.04238  ok
2999  1735336500000  1.04238  1.04253  1.04209  1.04212  ok

In [11]:
def calc_linear_regression(symbol, timeframe):
    """Calculate the linear regression for the given symbol and timeframe.

    Args:
        symbol (str): The trading symbol.
        timeframe (str): The timeframe for the linear regression.
    """
    price_data = PriceData(LoginManager())
    ohlc = price_data.fetch_market_data(symbol, timeframe)
    df = pd.DataFrame(ohlc)
    df.set_index("t", inplace=True)
    df.ta.linreg(close="c", length=14, append=True)
    return df["LR_14"].iloc[-1] - df["LR_14"].iloc[-2]

In [12]:
linear_reg_1H = calc_linear_regression("BTCUSDC", 60)
linear_reg_15M = calc_linear_regression("BTCUSDC", 15)

print(f"Linear regression 1H: {linear_reg_1H}")
print(f"Linear regression 15M: {linear_reg_15M}")

2024-12-28 21:07:05,687 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-28 21:07:06,325 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /market-data-api/None/api/trading-view/history?symbol=BTCUSDC&resolution=60&from=1733638025&to=1735438025&shouldRetrieveOnlyFromCache=true&countback=500 HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /market-data-api/None/api/trading-view/history?symbol=BTCUSDC&resolution=60&from=1733638025&to=1735438025&shouldRetrieveOnlyFromCache=true&countback=500 HTTP/11" 200 None

2024-12-28 21:07:06,337 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-28 21:07:06,746 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /market-data-api/None/api/trading-view/history?symbol=BTCUSDC&resolution=15&from=1734988026&to=1735438026&shouldRetrieveOnlyFromCache=true&countback=500 HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /market-data-api/None/api/trading-view/history?symbol=BTCUSDC&resolution=15&from=1734988026&to=1735438026&shouldRetrieveOnlyFromCache=true&countback=500 HTTP/11" 200 None
Linear regression 1H: -37.98681318690069
Linear regression 15M: -53.955824175762245

In [18]:
open_positions = utils.fetch_open_positions_once(login_manager)
print(json.dumps(open_positions, indent=4))

2024-12-28 21:18:06,553 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-28 21:18:07,046 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/open-positions HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/open-positions HTTP/11" 200 None
{
    "positions": [
        {
            "id": "W963704386443774",
            "symbol": "BTCUSDC",
            "alias": "BTCUSDC",
            "volume": 0.01,
            "side": "BUY",
            "openTime": "2024-12-29T01:28:13",
            "openTimeMillis": 1735435693621,
            "openPrice": 94987.7,
            "stopLoss": 94709.1,
            "takeProfit": 97451.41,
            "trailingDistance": 0,
            "swap": 0.0,
            "profit": -0.05,
            "netProfit": -0.05,
            "currentPrice": 94982.7,
            "commission": 0.0,
            "positions": [
                {
                    "id": "W963704386443774",
                    "symbol": "BTCUSDC",
                    "alias": "BTCUSDC",
                    "volume": "0.01",
                    "oldPartialVolume": null,
                    "side": "BUY",
                    "openTime": "2024-12-29T01:28:13",
                    "openPrice": "94987.70",
                    "swap": "0.00",
                    "profit": "-0.05",
                    "netProfit": "-0.05",
                    "currentPrice": "94982.70",
                    "commission": "0.00"
                }
            ]
        }
    ]
}

In [13]:
price_data = PriceData()
symbol = "BTCUSDC"
ohlc = price_data.fetch_market_data(login_manager, symbol, 5)
df = pd.DataFrame(ohlc).set_index("t")
stoch_rsi = df.ta.stochrsi(high="h", low="l", close="c", length=14)
stoch_rsi.tail()

2024-12-29 11:59:31,858 - root - INFO - Fetching market data for symbol: BTCUSDC, timeframe 5

Fetching market data for symbol: BTCUSDC, timeframe 5

2024-12-29 11:59:31,861 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-29 11:59:32,248 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/history?symbol=BTCUSDC&resolution=5&from=1735341571&to=1735491571&shouldRetrieveOnlyFromCache=true&countback=500 HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /market-data-api/82b821d8-eeff-4352-ae2a-753c1daf8546/api/trading-view/history?symbol=BTCUSDC&resolution=5&from=1735341571&to=1735491571&shouldRetrieveOnlyFromCache=true&countback=500 HTTP/11" 200 None

               STOCHRSIk_14_14_3_3  STOCHRSId_14_14_3_3
t
1735490100000         5.033011e-14         7.006741e-14
1735490400000         6.319288e+00         2.106429e+00
1735490700000         1.655694e+01         7.625410e+00
1735491000000         3.089054e+01         1.792226e+01
1735491300000         4.039455e+01         2.928068e+01

In [6]:
price_data = PriceData()
symbol = "EURUSD"
market_watch = price_data.fetch_market_watch(login_manager, symbol)
print(symbol, json.dumps(market_watch, indent=4))

2024-12-30 10:03:09,340 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): platform.citytradersimperium.com:443

Starting new HTTPS connection (1): platform.citytradersimperium.com:443

2024-12-30 10:03:09,538 - urllib3.connectionpool - DEBUG - https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/quotations?symbols=EURUSD HTTP/11" 200 None

https://platform.citytradersimperium.com:443 "GET /mtr-api/82b821d8-eeff-4352-ae2a-753c1daf8546/quotations?symbols=EURUSD HTTP/11" 200 None
EURUSD [
    {
        "symbol": "EURUSD",
        "alias": "EURUSD",
        "bid": "1.04043",
        "ask": "1.04045",
        "change": "-0.24",
        "high": "1.04583",
        "low": "1.03799",
        "timestampSec": 1735570989,
        "timestampMs": 1735570989089
    }
]